### ISSUE TITLE
有个报错，不清楚原因

### ISSUE THREAD

**Issue by wutongshufqw** [hsyhhssyy/amiyabot-hsyhhssyy-emoji-stat#1]
![CN_V3MYOM2N)JKIXII3@ VC](https://user-images.githubusercontent.com/87960738/213636411-09b02939-a9b0-45fe-b7d5-7b94ebf73bd5.PNG)
是在这里出现的
![image](https://user-images.githubusercontent.com/87960738/213636626-8b06cd9d-3ac7-4336-a540-9e6d803b36b5.png)
不清楚具体原因

**Comment by hsyhhssyy** [comment]
我盲猜是图文混发的一条消息如果被判定为emoji，会触发一个这样的错误，我去试一下

**Comment by hsyhhssyy** [comment]
经过试验，我猜测是因为发送了不认识的图片格式导致的。
新的1.5版本尝试解决了这个问题，你可以更新一下试试看看好了没有。

**Comment by wutongshufqw** [comment]
好的，谢谢作者大大

**Comment by hsyhhssyy** [comment]
如果过几天还没发现同样的问题的话，我就关掉这个Issue
