### ISSUE TITLE
兔兔使用MySQL数据库时无法安装该项目插件

### ISSUE THREAD

**Issue by m4pleX** [hsyhhssyy/amiyabot-hsyhhssyy-emoji-stat#2]
在安装失败的同时控制台会出现以下报错:
ModuleNotFoundError: No module named '_sqlite3'
并且安装您的另外一个插件 词云统计 时也出现这个报错。

**Comment by hsyhhssyy** [comment]
我想问一下，您是代码安装还是可执行文件安装？

**Comment by m4pleX** [comment]
代码安装

**Comment by hsyhhssyy** [comment]
python从2.5版本开始就自带sqlite3模块了，您这边使用代码安装还没有sqlite3模块，您是通过什么方式安装的Python我能了解一下吗？
不过不管怎样，您可以试试通过执行 pip install db-sqlite3 或者 pip install db-sqlite3 去安装sqlite来看看能不能解决这个问题。

**Comment by hsyhhssyy** [comment]
或者，你是不是系统安装不了sqlite？
你用的是centos？
这几个插件需要用sqlite存储数据，目前暂不支持移动到mysql中

**Comment by m4pleX** [comment]
我系统为0debian11，之前尝试过先安装sqlite，然后再重新编译安装Python3.8，刚刚pip安装了db-sqlite3后依旧报错没有_sqlite3模块。

**Comment by m4pleX** [comment]
正因为我发现我的amiyabot使用sqlite作为数据库时会提示缺少_sqlite3，导致无法正常工作。所以我选择放弃使用sqlite3作为amiyabot的数据库，改用mysql就正确运行amiyabot了，只不过依旧提示缺少_sqlite3模块，并且除了词云统计和图片记录员其它功能都正常安装和使用。

**Comment by m4pleX** [comment]
import sqlite3
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/python38/lib/python3.8/sqlite3/__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *
  File "/root/python38/lib/python3.8/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ModuleNotFoundError: No module named '_sqlite3'

**Comment by m4pleX** [comment]
经过我刚刚检索的资料以及实践，看起来编译安装的Python都会缺少_sqlite模块，apt安装的不会缺少，这应该是Python的问题。

**Comment by m4pleX** [comment]
另外，如果编译安装Python，在./configure时需加上选项--enable-loadable-sqlite-extensions，才能正确import sqlite3从而解决这个问题

**Comment by hsyhhssyy** [comment]
> 

6啊
