### ISSUE TITLE
水图功能无法和图片记录员功能一起关闭

### ISSUE THREAD

**Issue by niucattle** [hsyhhssyy/amiyabot-hsyhhssyy-emoji-stat#3]
![$VBA7X6)S 8X4VTA(HZDD@H](https://user-images.githubusercontent.com/118875129/222871798-4fe9bb32-3e52-4798-b53e-3347f0eb2015.png)

**Comment by niucattle** [comment]
好像只能在插件打开的时候单独关闭

**Comment by hsyhhssyy** [comment]
测试了一下，确实
现在已经更新了新版，解决了这个问题，更新一下试试就好了。
