### ISSUE TITLE
数据库访问冲突

### ISSUE THREAD

**Issue by wutongshufqw** [hsyhhssyy/amiyabot-hsyhhssyy-emoji-stat#4]
这个插件经常会报错database is locked，用兔兔核心提供的数据库工具类会不会更好

**Comment by hsyhhssyy** [comment]
不在兔兔里定义的db对象还要考虑用户用的是mysql还是sqlite，而且如果有一天兔兔支持了别的数据库还需要支持别的，会比较麻烦。

不过关于这个问题，兔兔roadmap里已经有一个解决方案了，我在考虑等那个。

**Comment by hsyhhssyy** [comment]
单纯解决lock问题，也可以通过规划线程来解决，但是我最近在研究GPT那个插件的新功能，还没功夫处理这个。

**Comment by wutongshufqw** [comment]
佬，我已经写好了，你看看，我自己这里测试了一阵子，已经不会阻塞了

**Comment by hsyhhssyy** [comment]
看到了，我在隔壁merge了，但是你应该是没做数据迁移吧

**Comment by wutongshufqw** [comment]
没有做，但是和之前的数据兼容，数据都在，之前的数据都保留了并且能获取到

**Comment by wutongshufqw** [comment]
我是照着数据库写的数据模型
